// InstanceManager
export const GET_INSTANCES = 'GET_INSTANCES';
export const ADD_INSTANCE = 'ADD_INSTANCE';
export const DELETE_INSTANCE = 'DELETE_INSTANCE';
export const SHOW_INSTANCE_WINDOW = 'SHOW_INSTANCE_WINDOW';
export const CALL_INSTANCE_FUNCTION = 'CALL_INSTANCE_FUNCTION';

// Application
export const SET_APPLICATION_OPTIONS = 'SET_APPLICATION_OPTIONS';
export const GET_APPLICATION_INFO = 'GET_APPLICATION_INFO';

// MAIN -> RENDERER
export const ON_SERVER_DISCONNECTED = 'ON_SERVER_DISCONNECTED';
export const ON_MENU_ITEM_CLICKED = 'ON_MENU_ITEM_CLICKED';
export const ON_APPLICATION_READY = 'ON_APPLICATION_READY';
